### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by socketryans** [socketryans/DBadder#2]
- [ ] Make input\output filenames changeable.
- [ ] Do something cool.
- [x] Create completed mark.
